### ISSUE TITLE
Allow dots in address

### ISSUE THREAD

**Issue by bradvogel** [FogCreek/email-addresses#14]
This is valid:

```
> addrs.parseOneAddress('validemail.@gmail.com')
null
```

**Comment by jackbowman** [comment]
Depends on what you mean by valid.

According to the RFCs, it is not a valid email address. See the production for a "dot-atom". See also the "is_email" library which also recognizes this as an invalid email address: https://github.com/FogCreek/email-addresses/blob/master/test/tests.xml#L174 .

Now, you may very well be able to send emails with recipients with such email addresses, so in some sense it is valid. Remember that this library can only detect what is technically a valid email address in terms of format. People are breaking these rules all the time, and mail agents may be very liberal with what they accept from direct user input.

I don't intend to add exceptions to this library unless there's a good reason for doing so.

**Comment by bradvogel** [comment]
Ok, makes sense. FWIW I filed https://github.com/chriso/validator.js/issues/404 against validator and they added the exception. But I completely understand if you'd like keep this library more pure. Thanks for the explanation!
